fix: export the spandump as json
lumigo-io/opentelemetry-java-distro pull request #11
Opened 2023-02-28 22:51 UTC by AlmogBaku

This change closes #5 by exporting the spandump as json

2023-03-01 17:07 UTC, AlmogBaku commented
@mmanciop this is ready for review

2023-03-06 11:14 UTC, mmanciop requested changes

2023-03-09 10:28 UTC, AlmogBaku commented on custom/src/main/java/io/lumigo/javaagent/FileLoggingSpanExporter.java
> +      generator.close();
both `.createGenerator(outputStream)`, `traceRequestMarshaler.writeJsonTo(generator);`, and `outputStream.write("\r\n".getBytes());` can throw `IOException`. therefore I it's valid.

2023-03-09 10:36 UTC, AlmogBaku commented on custom/src/main/java/io/lumigo/javaagent/FileLoggingSpanExporter.java
> +      outputStream.close();
I can't use `finally` since there's a need for a try-catch for the close. I just created an additional try-catch

2023-03-09 11:40 UTC, mmanciop requested changes
We need to implement this without pulling in a 3rd-party dependency. See if you can reuse what https://github.com/open-telemetry/opentelemetry-java/blob/dd40fbeab7735e64b886e7e2f1dd202b8d4827ce/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java#L22 does

2023-03-09 11:40 UTC, mmanciop commented on build.gradle
> +      jackson                    : "2.14.2",
We should never add a non-opentelemetry dependency if we can avoid it, _especially_ if it is such a common one like Jackson. This is effectively a guarantee for hard-to-debug classloading nightmares.

2023-03-09 15:56 UTC, merged