feat: add jedis-1.4 instrumentation
lumigo-io/opentelemetry-java-distro pull request #142
Opened 2023-10-10 07:23 UTC by saartochner

2023-10-10 07:24 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/build.gradle
> +// TODO: I'm not sure what to do here
Hi Ken,
I tried my best here, but I'm not sure that I did it right.
WDYT?

2023-10-10 07:24 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisConnectionInstrumentation.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisDbAttributesGetter.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisInstrumentation.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisInstrumentationModule.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisNetAttributesGetter.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisRequest.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisRequestContext.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisSingletons.java
> +/*
RAW COPY

2023-10-10 07:25 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisClientTest.java
> +/*
RAW COPY

2023-10-10 07:43 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/build.gradle
> +dependencies {
Hi Ken,
I tried my best here, but I'm not sure that I did it right.
WDYT?

2023-10-10 08:23 UTC, saartochner commented
I saw that the GitHub action `Version Testing / push-branch (push)` is failing in other PRs as well.
Is it mandatory? flaky?

2023-10-10 08:37 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisClientTest.java
> +/*
Added the test: `setSetTransactionCommand`

2023-10-10 13:20 UTC, kenfinnigan commented
Usually it's only meant to fail when creating a PR. I think there are so many instrumentation versions to test, it can sometimes get flaky.

I looked at what's changed for this instrumentation, and I don't think we need to copy anything from upstream. All we need is a config customizer like we have for JDBC: https://github.com/lumigo-io/opentelemetry-java-distro/blob/main/instrumentation/jdbc/javaagent/src/main/java/io/lumigo/javaagent/instrumentation/jdbc/JdbcConfigCustomizer.java

You could copy the same class, as it's the same variable that needs to be overridden to prevent DB statement sanitization

2023-10-12 13:34 UTC, saartochner commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/lumigo/javaagent/instrumentation/jedis/v1_4/JedisConfigCustomizer.java
> +/*
This file was copied from `opentelemetry-java-distro/instrumentation/jdbc/javaagent/src/main/java/io/lumigo/javaagent/instrumentation/jdbc/JdbcConfigCustomizer.java`

2023-10-12 14:15 UTC, kenfinnigan requested changes

2023-10-12 14:15 UTC, kenfinnigan commented on instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/lumigo/javaagent/instrumentation/jedis/v1_4/JedisInstrumentationModule.java
> +public class JedisInstrumentationModule extends InstrumentationModule {
This class shouldn't be needed, as we're not overriding any instrumentation from upstream.

Our config customizer can be added without needing an instrumentation module

2023-10-12 19:43 UTC, kenfinnigan commented on instrumentation/jedis/jedis-1.4/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/README.md
> +# Jedis tests
Sure, we can leave it in

2023-10-12 19:44 UTC, kenfinnigan approved these changes

2023-10-12 19:44 UTC, merged